common:
  seed: 1234
  vis_GPU: '0' #single GPU compatibility
  log_path: '/data/knee_mri8/Francesco/deep_bone_aging/experiments/training/logs/'
  save_path: '/data/knee_mri8/Francesco/deep_bone_aging/experiments/training/ckpt/'
  print_freq: 50
  qsub: 0

data_train:
  data_root: '/data/knee_mri8/Francesco/deep_bone_aging/pickle_files/train.pickle'
  batch_size: 8
  im_dims: !!python/tuple [224, 224]
  crop : !!python/tuple [0, 0, 0, 0]
  num_classes: 2
  idx_classes : [0]
  num_channels: 3
  normalization_file: ' '
  evaluate_mode: False
  input_type: 'float32'
  target_type: 'float32'
  predict_remodeling: False
  add_noise: False

data_val:
  data_root : '/data/knee_mri8/Francesco/deep_bone_aging/pickle_files/val.pickle'
  batch_size: 8
  im_dims: !!python/tuple [224, 224]
  crop : !!python/tuple [0, 0, 0, 0]
  num_classes: 2
  idx_classes : [0]
  num_channels: 3
  normalization_file: ' '
  evaluate_mode: False
  input_type: 'float32'
  target_type: 'float32'
  predict_remodeling: False
  add_noise: False

dataLoader_folder: 'dataLoader'
learn:
  max_steps: 500000 # instead of epochs
  lr : 0.00001
  optimizer: 'adam'
  loss: 'mse_loss'
  metrics: 'mae_mse_rmse_ssim'
  monitor: 'mae'
  weights: [1]
  num_classes: 2
  dataloader: 'data_loader'
  comp: ['spherical_enc']
  key_slice: !!python/tuple [0, 0, 0]
  patience: 30 # in number of validation runs
  keep_prob : 0.95
  val_freq : 150 # in steps

model_folder: VNet
model: 'VNet'
model_params:
# github.com/MiguelMonteiro/VNet-Tensorflow
  num_classes: 1
  num_channels : 16
  num_levels : 4
  num_convolutions : !!python/tuple [3, 4, 3, 4]
  bottom_convolutions : 2

pretrain:
  only_infer: False
  flag: False
  ckpt: '' 
  # ckpt: '/data/knee_mri8/Francesco/deep_bone_aging/experiments/training/ckpt/0409134909_train_mae_ssim_noisy'
  # ckpt: '/data/knee_mri8/Francesco/deep_bone_aging/experiments/training/ckpt/0409134218_train_mse_noisy'
  # ckpt: '/data/knee_mri8/Francesco/deep_bone_aging/experiments/training/ckpt/0409135136_train_mae_ssim_remodeling'
  # ckpt: '/data/knee_mri8/Francesco/deep_bone_aging/experiments/training/ckpt/0409130406_mse_loss_remodeling'
  